print('creator : mr.skandiara')
print(' ')
print('  /\  /\ ')
print(' /  \/  \ ')
print('/        \ ')
print(' ')
print(' ')
print(' ')
print(' ')
print(' ')
print('1 = Total')
print('2 = multiplication')
print('3 = Division')
print('4 = subtraction')
pc = input("pls enter the part code:")
if pc  =  1:
    t1 = input("enter one number:")
    t2 = input("enter two number:")
    print(int(t1) + int(t2))
elif pc = 2:
    m1 = input("enter one number:")
    m2 = input("enter two number:")
    print(int(m1) * int(m2))
elif pc = 3:
    d1 = input("enter one number:")
    d2 = input("enter two number:")
    print(int(d1) / int(d2))
elif pc = 4:
    s1 = input("enter one number:")
    s2 = input("enter two number:")
    print(int(s1) - int(s2))
else:
    print("1 or 2 or 3 or 4")
    print(' ')
    print(' ')
pc = input("pls enter the part code again:")